[package]
name = "kiwi"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.9", default-features = false, features = ["http1", "http2", "tokio"] }
bytes = "1.11.1"
clap = { version = "4.6.1", features = ["derive"] }
notify = "8.2.0"
reqwest = { version = "0.13.4", default-features = false, features = ["rustls"] }
tokio = { version = "1.52.3", features = ["macros", "net", "rt", "rt-multi-thread"] }
typst = "0.15.1"
typst-html = "0.15.1"
typst-kit = { version = "0.15.1", features = ["system-files", "universe-packages", "embedded-fonts", "scan-fonts", "emit-diagnostics", "datetime"] }
typst-macros = "0.15.1"
typst-library = "0.15.1"
typst-utils = "0.15.1"
walkdir = "2.5.0"
rustc-hash = "2.1.2"
tower-http = { version = "0.6.11", features = ["fs"] }
tower-livereload = "0.10.3"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
tower = "0.5.3"
