[package]
name = "kiwi"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.9", default-features = false, features = ["http1", "http2", "tokio"] }
bytes = "1.11.1"
clap = { version = "4.6.1", features = ["derive"] }
http = "1.4.1"
notify = "8.2.0"
reqwest = { version = "0.13.4", default-features = false, features = ["rustls"] }
tokio = { version = "1.52.3", features = ["macros", "net", "rt", "rt-multi-thread"] }
typst = { git = "https://github.com/typst/typst.git" }
typst-html = { git = "https://github.com/typst/typst.git" }
typst-kit = { git = "https://github.com/typst/typst.git", features = ["system-files", "universe-packages", "embedded-fonts", "scan-fonts", "emit-diagnostics", "datetime"] }
typst-macros = { git = "https://github.com/typst/typst.git" }
typst-library = { git = "https://github.com/typst/typst.git" }
typst-utils = { git = "https://github.com/typst/typst.git" }
walkdir = "2.5.0"
